"""Atualiza relacionamento entre fornecedor e conta

Revision ID: 163b33efd561
Revises: cab17a9e56c6
Create Date: 2024-11-30 20:23:00.665364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163b33efd561'
down_revision: Union[str, None] = 'cab17a9e56c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
