"""Adiciona data previsao em uma conta

Revision ID: 3e3c4ee43712
Revises: 98133e1e8f96
Create Date: 2024-12-27 19:40:02.632703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3c4ee43712'
down_revision: Union[str, None] = '98133e1e8f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('data_previsao', sa.DateTime(), nullable=True))
    op.execute("UPDATE contas_a_pagar_e_receber SET data_previsao = now()")
    op.alter_column('contas_a_pagar_e_receber', 'data_previsao', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar_e_receber', 'data_previsao')
    # ### end Alembic commands ###
